### ISSUE TITLE
Upon sending a message, print the user's message to the console with current timestamp

### ISSUE THREAD

**Issue by vwroddy** [Limvot/Serif#11]
Story is to allow the user's messages to be displayed as part of the ongoing chat.

Acceptance Criteria:
Given You are running the application via gradle
And you are authenticated + have set a room
When you run the command `send <message>` to that room
Then the application should print your message to the console with current timestamp

Notes:
- Printout should have current timestamp, message, and username (If getting display name isnt implemented yet, use hardcoded "Me")

**Comment by Limvot** [comment]
Spirit of issue completed
