### ISSUE TITLE
Upon logging into the application, execute a sync to get joined rooms and recent events

### ISSUE THREAD

**Issue by vwroddy** [Limvot/Serif#7]
Story is to print out the user's rooms and count of unread messages in each after successfully logging in.

Acceptance Criteria:
Given You are running the application via gradle
When you have successfully authenticated with username/password (could be hardcoded, this issue can be done before #5 )
Then the application should execute a sync call
And the application should print out the list of rooms the user has joined, with counts of unread messages

Notes:
- See https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-sync
- (If not already done) Will need to change how we are running the application so that it stays running, rather than executing like a one-time script.

**Comment by Limvot** [comment]
Working on this in the syncing branch. Have an initial sketch on top of Lotusronin's message sending code, but it needs more work.
