### ISSUE TITLE
Enable user to set the room in which to send/receive messages

### ISSUE THREAD

**Issue by vwroddy** [Limvot/Serif#8]
Story is to allow the user to set what room theyre in, so that when they send a message it goes to that room, and when the user receives messages from that room, they messages are printed to the console. 

Acceptance Criteria:
Given You are running the application via gradle
And you have successfully authenticated with username/password 
When you have access to a room
Then you should be able to run the command `set-room <room alias>` for that room
And any messages sent or received will utilize the room ID of that room

Notes:
- To get room ID from room alias, see https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-directory-room-roomalias

**Comment by Limvot** [comment]
Fixed with sync #17!
